package GUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import LogicClient.MD5_hash;
import LogicClient.User;
import ClientCommunication.SocketClient;
import static GUI.GameUI.gameui;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Window;
import static java.lang.Thread.sleep;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author up201303749
 */
public class UIinicial extends javax.swing.JFrame {

    /**
     * Creates new form UIinicial
     */
    public static UIinicial main = new UIinicial();
    String username = new String();
    JPanel backvalue = new JPanel();
    String password = new String();
    String oldpassword = new String();
    String mail = new String();
    String name = new String();
    public static User user = null;

    public UIinicial() {
        initComponents();
        defaultpanel();
    }

    private void defaultpanel() {
        setContentPane(Inicial);

        invalidate();
        validate();
    }

    private void InicialSetDefault() {
        jTextFieldInicial.setText("Enter username...");
        jPasswordInicial.setText("Password");
    }

    public static User getUser() {
        return main.user;
    }

    private void SignupSetDefault() {
        emailTextSignup.setText("Enter e-mail...");
        usernameTextSignup.setText("Enter username...");
        jPasswordSignup.setText("Password");
        AnswerQuestionSignup.setText("Answer Here...");
        usernameTextSignup1.setText("Enter name...");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Select your question here...", "Item1", "Item2", "ItemN"}));
    }

    private void ForgotPasswordSetDefault() {
        emailText1.setText("Enter e-mail...");
        usernameText4.setText("Enter username...");
        jPasswordField5.setText("Password");
        jPasswordField6.setText("Password");
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Select your question here...", "Item1", "Item2", "ItemN"}));
        usernameText5.setText("Answer Here...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        Signup = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        password3 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jPasswordSignup = new javax.swing.JPasswordField();
        usernameTextSignup = new javax.swing.JFormattedTextField();
        emailTextSignup = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        AnswerQuestionSignup = new javax.swing.JFormattedTextField();
        login2 = new javax.swing.JButton();
        Ads = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        goback3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usernameTextSignup1 = new javax.swing.JFormattedTextField();
        Inicial = new javax.swing.JPanel();
        forgotPw = new javax.swing.JButton();
        login1 = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        jPasswordInicial = new javax.swing.JPasswordField();
        playGuest = new javax.swing.JButton();
        newAcc1 = new javax.swing.JButton();
        jTextFieldInicial = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel3 = new javax.swing.JLabel();
        GuestIntro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        JoinGame = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        goback2 = new javax.swing.JButton();
        ForgotPassword = new javax.swing.JPanel();
        title5 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        password4 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        jPasswordField5 = new javax.swing.JPasswordField();
        usernameText4 = new javax.swing.JFormattedTextField();
        emailText1 = new javax.swing.JFormattedTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        usernameText5 = new javax.swing.JFormattedTextField();
        login3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        goback1 = new javax.swing.JButton();
        password5 = new javax.swing.JLabel();
        jPasswordField6 = new javax.swing.JPasswordField();
        Intro = new javax.swing.JPanel();
        goback = new javax.swing.JButton();
        newAcc2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        PlayersOnline1 = new javax.swing.JButton();
        Rankings1 = new javax.swing.JButton();
        JoinGame1 = new javax.swing.JButton();
        CreateGame1 = new javax.swing.JButton();
        welcome1 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        Ads1 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        GameJoined = new javax.swing.JPanel();
        welcome2 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        goback4 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainFrame");
        setResizable(false);
        setSize(new java.awt.Dimension(450, 350));

        Signup.setPreferredSize(new java.awt.Dimension(450, 350));

        title3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        title3.setText("Battleship");
        title3.setAlignmentX(0.5F);
        title3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        title3.setIconTextGap(7);
        title3.setPreferredSize(new java.awt.Dimension(100, 19));

        username2.setText("username");

        password3.setText("password");

        email.setText("E-mail");

        jPasswordSignup.setText("Password");
        jPasswordSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordSignupFocusGained(evt);
            }
        });
        jPasswordSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordSignupActionPerformed(evt);
            }
        });

        usernameTextSignup.setText("Enter username...");
        usernameTextSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextSignupFocusGained(evt);
            }
        });
        usernameTextSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextSignupActionPerformed(evt);
            }
        });

        emailTextSignup.setText("Enter e-mail...");
        emailTextSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextSignupFocusGained(evt);
            }
        });
        emailTextSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextSignupActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your question here...", "Item1", "Item2", "ItemN" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        AnswerQuestionSignup.setText("Answer Here...");
        AnswerQuestionSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AnswerQuestionSignupFocusGained(evt);
            }
        });
        AnswerQuestionSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerQuestionSignupActionPerformed(evt);
            }
        });

        login2.setText("Sign Up");
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });

        jTextPane5.setText("Publicidade");
        jTextPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane5.setEnabled(false);
        jTextPane5.setFocusable(false);
        Ads.setViewportView(jTextPane5);

        goback3.setText("Go Back");
        goback3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goback3ActionPerformed(evt);
            }
        });

        jLabel2.setText("name");

        usernameTextSignup1.setText("Enter name...");
        usernameTextSignup1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextSignup1FocusGained(evt);
            }
        });
        usernameTextSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextSignup1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignupLayout = new javax.swing.GroupLayout(Signup);
        Signup.setLayout(SignupLayout);
        SignupLayout.setHorizontalGroup(
            SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupLayout.createSequentialGroup()
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addContainerGap(146, Short.MAX_VALUE)
                        .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupLayout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SignupLayout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email)
                                    .addComponent(username2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(password3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(usernameTextSignup, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordSignup, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTextSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameTextSignup1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(SignupLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(login2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                                .addComponent(goback3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SignupLayout.createSequentialGroup()
                                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AnswerQuestionSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(Ads, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        SignupLayout.setVerticalGroup(
            SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email)
                            .addComponent(emailTextSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username2)
                            .addComponent(usernameTextSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(usernameTextSignup1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(AnswerQuestionSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(login2)
                            .addComponent(goback3))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addComponent(Ads, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addContainerGap(134, Short.MAX_VALUE))))
        );

        Inicial.setPreferredSize(new java.awt.Dimension(450, 350));
        Inicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InicialMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InicialMouseEntered(evt);
            }
        });

        forgotPw.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        forgotPw.setText("Forgot Password?");
        forgotPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPwActionPerformed(evt);
            }
        });

        login1.setLabel("Login");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });

        title2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        title2.setText("Battleship");
        title2.setAlignmentX(0.5F);
        title2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        title2.setIconTextGap(7);
        title2.setPreferredSize(new java.awt.Dimension(100, 19));

        username1.setText("username");

        password2.setText("password");

        jPasswordInicial.setText("Password");
        jPasswordInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordInicialFocusGained(evt);
            }
        });
        jPasswordInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordInicialActionPerformed(evt);
            }
        });

        playGuest.setText("Play as guest");
        playGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGuestActionPerformed(evt);
            }
        });

        newAcc1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        newAcc1.setText("New account?");
        newAcc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAcc1ActionPerformed(evt);
            }
        });

        jTextFieldInicial.setText("Enter username...");
        jTextFieldInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldInicialFocusGained(evt);
            }
        });
        jTextFieldInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInicialActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ads/Cola.png"))); // NOI18N

        javax.swing.GroupLayout InicialLayout = new javax.swing.GroupLayout(Inicial);
        Inicial.setLayout(InicialLayout);
        InicialLayout.setHorizontalGroup(
            InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InicialLayout.createSequentialGroup()
                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicialLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newAcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(forgotPw, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicialLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(username1)
                                    .addComponent(password2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(jPasswordInicial)))
                            .addGroup(InicialLayout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicialLayout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(playGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        InicialLayout.setVerticalGroup(
            InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicialLayout.createSequentialGroup()
                .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InicialLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(login1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playGuest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newAcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forgotPw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        GuestIntro.setPreferredSize(new java.awt.Dimension(450, 350));

        jTextPane1.setText("Games Running");
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane1.setEnabled(false);
        jTextPane1.setFocusable(false);
        jScrollPane1.setViewportView(jTextPane1);

        JoinGame.setText("Join Game");
        JoinGame.setEnabled(false);
        JoinGame.setFocusPainted(false);
        JoinGame.setFocusable(false);
        JoinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinGameActionPerformed(evt);
            }
        });

        welcome.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        welcome.setText("Welcome guest!");

        title4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        title4.setText("Battleship");
        title4.setAlignmentX(0.5F);
        title4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        title4.setIconTextGap(7);
        title4.setPreferredSize(new java.awt.Dimension(100, 19));

        jTextPane2.setText("Publicidade");
        jTextPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane2.setEnabled(false);
        jTextPane2.setFocusable(false);
        jScrollPane2.setViewportView(jTextPane2);

        goback2.setText("Go Back");
        goback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goback2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GuestIntroLayout = new javax.swing.GroupLayout(GuestIntro);
        GuestIntro.setLayout(GuestIntroLayout);
        GuestIntroLayout.setHorizontalGroup(
            GuestIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestIntroLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(GuestIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GuestIntroLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GuestIntroLayout.createSequentialGroup()
                        .addGroup(GuestIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JoinGame, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GuestIntroLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(goback2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))))
            .addGroup(GuestIntroLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(GuestIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcome))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        GuestIntroLayout.setVerticalGroup(
            GuestIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestIntroLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(GuestIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(GuestIntroLayout.createSequentialGroup()
                        .addComponent(JoinGame, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goback2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        ForgotPassword.setPreferredSize(new java.awt.Dimension(450, 350));

        title5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        title5.setText("Battleship");
        title5.setAlignmentX(0.5F);
        title5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        title5.setIconTextGap(7);
        title5.setPreferredSize(new java.awt.Dimension(100, 19));

        username3.setText("username");

        password4.setText("old password");

        email1.setText("E-mail");

        jPasswordField5.setText("Password");
        jPasswordField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField5FocusGained(evt);
            }
        });
        jPasswordField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField5ActionPerformed(evt);
            }
        });

        usernameText4.setText("Enter username...");
        usernameText4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameText4FocusGained(evt);
            }
        });
        usernameText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameText4ActionPerformed(evt);
            }
        });

        emailText1.setText("Enter e-mail...");
        emailText1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailText1FocusGained(evt);
            }
        });
        emailText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailText1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your question here...", "Item1", "Item2", "ItemN" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        usernameText5.setText("Answer Here...");
        usernameText5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameText5FocusGained(evt);
            }
        });
        usernameText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameText5ActionPerformed(evt);
            }
        });

        login3.setText("Change password");
        login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Forgot Password?");

        goback1.setText("Go Back");
        goback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goback1ActionPerformed(evt);
            }
        });

        password5.setText("new password");

        jPasswordField6.setText("Password");
        jPasswordField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField6FocusGained(evt);
            }
        });
        jPasswordField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ForgotPasswordLayout = new javax.swing.GroupLayout(ForgotPassword);
        ForgotPassword.setLayout(ForgotPasswordLayout);
        ForgotPasswordLayout.setHorizontalGroup(
            ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForgotPasswordLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(ForgotPasswordLayout.createSequentialGroup()
                            .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email1)
                                .addComponent(username3)
                                .addComponent(password4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(password5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(12, 12, 12)
                            .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(usernameText4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailText1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(jPasswordField6)))
                        .addComponent(usernameText5)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ForgotPasswordLayout.createSequentialGroup()
                            .addComponent(login3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addComponent(goback1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(ForgotPasswordLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        ForgotPasswordLayout.setVerticalGroup(
            ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForgotPasswordLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email1)
                    .addComponent(emailText1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username3)
                    .addComponent(usernameText4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password4))
                .addGap(12, 12, 12)
                .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(usernameText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(ForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login3)
                    .addComponent(goback1))
                .addGap(21, 21, 21))
        );

        Intro.setPreferredSize(new java.awt.Dimension(450, 350));

        goback.setText("Go Back");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        newAcc2.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        newAcc2.setText("Change Profile");
        newAcc2.setEnabled(false);
        newAcc2.setFocusable(false);
        newAcc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAcc2ActionPerformed(evt);
            }
        });

        jTextPane3.setText("Chat Area");
        jTextPane3.setToolTipText("");
        jTextPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane3.setEnabled(false);
        jTextPane3.setFocusable(false);
        jScrollPane3.setViewportView(jTextPane3);

        jTextPane4.setText("Games Running");
        jTextPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane4.setEnabled(false);
        jTextPane4.setFocusable(false);
        jScrollPane4.setViewportView(jTextPane4);

        PlayersOnline1.setText("Players Online");
        PlayersOnline1.setEnabled(false);
        PlayersOnline1.setFocusPainted(false);
        PlayersOnline1.setFocusable(false);
        PlayersOnline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayersOnline1ActionPerformed(evt);
            }
        });

        Rankings1.setText("Rankings");
        Rankings1.setEnabled(false);
        Rankings1.setFocusable(false);
        Rankings1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rankings1ActionPerformed(evt);
            }
        });

        JoinGame1.setText("Join Game");
        JoinGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinGame1ActionPerformed(evt);
            }
        });

        CreateGame1.setText("Create Game");
        CreateGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateGame1ActionPerformed(evt);
            }
        });

        welcome1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        welcome1.setText("Welcome "+username+"!");

        title6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        title6.setText("Battleship");
        title6.setAlignmentX(0.5F);
        title6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        title6.setIconTextGap(7);
        title6.setPreferredSize(new java.awt.Dimension(100, 19));

        jTextPane6.setText("Publicidade");
        jTextPane6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane6.setEnabled(false);
        jTextPane6.setFocusable(false);
        Ads1.setViewportView(jTextPane6);

        javax.swing.GroupLayout IntroLayout = new javax.swing.GroupLayout(Intro);
        Intro.setLayout(IntroLayout);
        IntroLayout.setHorizontalGroup(
            IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroLayout.createSequentialGroup()
                        .addComponent(newAcc2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(goback, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Ads1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IntroLayout.createSequentialGroup()
                        .addGroup(IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcome1)
                            .addGroup(IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JoinGame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Rankings1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PlayersOnline1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CreateGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(IntroLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        IntroLayout.setVerticalGroup(
            IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(welcome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroLayout.createSequentialGroup()
                        .addComponent(CreateGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(JoinGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(Rankings1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(PlayersOnline1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newAcc2)
                            .addComponent(goback))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ads1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IntroLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        GameJoined.setPreferredSize(new java.awt.Dimension(450, 350));

        welcome2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        welcome2.setText("Waiting...");

        title7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        title7.setText("Battleship");
        title7.setAlignmentX(0.5F);
        title7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        title7.setIconTextGap(7);
        title7.setPreferredSize(new java.awt.Dimension(100, 19));

        jTextPane8.setText("Publicidade");
        jTextPane8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane8.setEnabled(false);
        jTextPane8.setFocusable(false);
        jScrollPane6.setViewportView(jTextPane8);

        goback4.setText("Go Back");
        goback4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goback4ActionPerformed(evt);
            }
        });

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Press to ready");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GameJoinedLayout = new javax.swing.GroupLayout(GameJoined);
        GameJoined.setLayout(GameJoinedLayout);
        GameJoinedLayout.setHorizontalGroup(
            GameJoinedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameJoinedLayout.createSequentialGroup()
                .addGroup(GameJoinedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameJoinedLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(goback4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GameJoinedLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GameJoinedLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameJoinedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(welcome2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GameJoinedLayout.setVerticalGroup(
            GameJoinedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameJoinedLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(welcome2)
                .addGap(43, 43, 43)
                .addGroup(GameJoinedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goback4)
                    .addComponent(jToggleButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jToggleButton1.getAccessibleContext().setAccessibleName("AreYouReady");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(GuestIntro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(Signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 13, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Intro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GameJoined, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(GuestIntro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(Signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Intro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GameJoined, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextSignupActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void AnswerQuestionSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerQuestionSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerQuestionSignupActionPerformed
    public static final Pattern VALID_EMAIL_ADDRESS_REGEX
            = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);

    public static boolean validate(String emailStr) {
        Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(emailStr);
        return matcher.find();
    }
    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        // TODO add your handling code here:
        if (jPasswordSignup.getText().isEmpty() || emailTextSignup.getText().isEmpty() || usernameTextSignup.getText().isEmpty() || usernameTextSignup1.getText().isEmpty()) {
            jOptionPane1.showMessageDialog(null, "Empty parameters");
        } else {
            username = usernameTextSignup.getText();
            name = usernameTextSignup1.getText();
            if (jPasswordSignup.getText().contains("&") || username.contains("&") || emailTextSignup.getText().contains("&") || name.contains("&")) {
                jOptionPane1.showMessageDialog(null, "Invalid caracter '&'");
                return;
            }
            if (validate(emailTextSignup.getText())) {
                mail = emailTextSignup.getText();
            } else {
                jOptionPane1.showMessageDialog(null, "Invalid mail");
                return;
            }

            jOptionPane1.setVisible(false);
            password = MD5_hash.MD5_hash(jPasswordSignup.getText());

            /*if (user!=null){
                try {
                    user.join();
                } catch (InterruptedException ex) {
                    Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }*/
            user = new User(username, password, mail, name, null);
            System.out.println(user);
            try {
                user.sendData("Signup");
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (user.getResultadoLogin() == 4) {
                    jOptionPane1.showMessageDialog(null, "Username already used!");
                } else if (user.getResultadoLogin() == 5) {
                    jOptionPane1.showMessageDialog(null, "Email already used!");
                } else {
                    setContentPane(Inicial);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            jOptionPane1.setVisible(false);

            backvalue = Inicial;

        }

    }//GEN-LAST:event_login2ActionPerformed

    private void JoinGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoinGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JoinGameActionPerformed

    private void usernameText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameText4ActionPerformed

    private void emailText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailText1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void usernameText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameText5ActionPerformed

    private void login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login3ActionPerformed
        // TODO add your handling code here:

        if (emailText1.getText().isEmpty() || usernameText4.getText().isEmpty() || jPasswordField5.getText().isEmpty()) {
            jOptionPane1.showMessageDialog(null, "Empty parameters");
        } else {
            mail = emailText1.getText();
            username = usernameText4.getText();
            oldpassword = MD5_hash.MD5_hash(jPasswordField5.getText());

            if (jPasswordField5.getText().contains("&")) {
                jOptionPane1.showMessageDialog(null, "Invalid caracter '&'");
                return;
            }

            jOptionPane1.setVisible(false);
            password = MD5_hash.MD5_hash(jPasswordField6.getText());

            user = new User(mail, username, oldpassword, null, password);

            try {
                user.sendData("ForgotPassword");
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (user.getResultadoRecoverPassword() == 2) {
                jOptionPane1.showMessageDialog(null, "Email doesn't exist!");
            } else if (user.getResultadoRecoverPassword() == 3) {
                jOptionPane1.showMessageDialog(null, "Username doesn't exist!");
            } else if (user.getResultadoRecoverPassword() == 4) {
                jOptionPane1.showMessageDialog(null, "Wrong Password!");
            } else if (user.getResultadoRecoverPassword() == 5) {
                jOptionPane1.showMessageDialog(null, "Email and Username aren't compatible!");
            } else {
                setContentPane(Inicial);
            }

            jOptionPane1.setVisible(false);
        }
        backvalue = Inicial;
    }//GEN-LAST:event_login3ActionPerformed

    private void newAcc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAcc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAcc2ActionPerformed

    private void PlayersOnline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayersOnline1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayersOnline1ActionPerformed

    private void Rankings1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rankings1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rankings1ActionPerformed

    private void JoinGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoinGame1ActionPerformed
        try {
            // TODO add your handling code here:
            user.JoinGame();
            user.lock.lock();
            try {
                user.join.await(); // releases lock and waits until doSomethingElse is called
            } finally {
                user.lock.unlock();
            }
            System.out.println("Unlocked");
            welcome2.setText(username + " vs " + user.getGameOpponent());
            gameui = new GameUI(username, user.getGameOpponent());
            gameui.setVisible(true);

        } catch (IOException ex) {
            Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_JoinGame1ActionPerformed

    private void CreateGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateGame1ActionPerformed
        // TODO add your handling code here:
        setContentPane(GameJoined);
        invalidate();
        validate();
        backvalue = Intro;
        jOptionPane1.showMessageDialog(null, "Waiting for opponents...");
        try {
            user.getGame();
            user.lock.lock();
            try {
                user.notFull.await(); // releases lock and waits until doSomethingElse is called
            } finally {
                user.lock.unlock();
            }
            System.out.println("Unlocked");
            welcome2.setText(username + " vs " + user.getGameOpponent());
            gameui = new GameUI(username, user.getGameOpponent());
            jOptionPane1.setVisible(false);
            gameui.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CreateGame1ActionPerformed

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        // TODO add your handling code here:
        InicialSetDefault();
        setContentPane(backvalue);
        invalidate();
        validate();
    }//GEN-LAST:event_gobackActionPerformed

    private void goback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goback1ActionPerformed
        // TODO add your handling code here:
        InicialSetDefault();
        setContentPane(backvalue);
        invalidate();
        validate();
    }//GEN-LAST:event_goback1ActionPerformed

    private void goback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goback2ActionPerformed
        // TODO add your handling code here:
        InicialSetDefault();
        setContentPane(backvalue);
        invalidate();
        validate();
    }//GEN-LAST:event_goback2ActionPerformed

    private void goback3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goback3ActionPerformed
        // TODO add your handling code here:
        InicialSetDefault();
        setContentPane(backvalue);
        invalidate();
        validate();
    }//GEN-LAST:event_goback3ActionPerformed

    private void usernameTextSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextSignupFocusGained
        // TODO add your handling code here:
        usernameTextSignup.setText("");
    }//GEN-LAST:event_usernameTextSignupFocusGained

    private void jPasswordSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordSignupFocusGained
        // TODO add your handling code here:
        jPasswordSignup.setText("");
    }//GEN-LAST:event_jPasswordSignupFocusGained

    private void emailTextSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextSignupActionPerformed

    private void emailTextSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextSignupFocusGained
        // TODO add your handling code here:
        emailTextSignup.setText("");
    }//GEN-LAST:event_emailTextSignupFocusGained

    private void AnswerQuestionSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnswerQuestionSignupFocusGained
        // TODO add your handling code here:
        AnswerQuestionSignup.setText("");
    }//GEN-LAST:event_AnswerQuestionSignupFocusGained

    private void emailText1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailText1FocusGained
        // TODO add your handling code here:
        emailText1.setText("");
    }//GEN-LAST:event_emailText1FocusGained

    private void usernameText4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameText4FocusGained
        // TODO add your handling code here:
        usernameText4.setText("");
    }//GEN-LAST:event_usernameText4FocusGained

    private void jPasswordField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordField5ActionPerformed

    private void usernameText5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameText5FocusGained
        // TODO add your handling code here:
        usernameText5.setText("");
    }//GEN-LAST:event_usernameText5FocusGained

    private void jPasswordField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField5FocusGained
        // TODO add your handling code here:
        jPasswordField5.setText("");
    }//GEN-LAST:event_jPasswordField5FocusGained

    private void jTextFieldInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInicialActionPerformed

    private void jTextFieldInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldInicialFocusGained
        // TODO add your handling code here:
        if (jTextFieldInicial.getText().equals("Enter username...")) {
            jTextFieldInicial.setText("");
        }
    }//GEN-LAST:event_jTextFieldInicialFocusGained

    private void newAcc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAcc1ActionPerformed
        setContentPane(Signup);
        invalidate();
        validate();
        backvalue = Inicial;
        SignupSetDefault();
    }//GEN-LAST:event_newAcc1ActionPerformed

    private void playGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGuestActionPerformed
        // TODO add your handling code here:
        setContentPane(GuestIntro);
        invalidate();
        validate();
        backvalue = Inicial;
    }//GEN-LAST:event_playGuestActionPerformed

    private void jPasswordInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordInicialActionPerformed

    private void jPasswordInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordInicialFocusGained
        // TODO add your handling code here:
        if (jPasswordInicial.getText().equals("Password")) {
            jPasswordInicial.setText("");
        }
    }//GEN-LAST:event_jPasswordInicialFocusGained

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldInicial.getText().isEmpty() || jPasswordInicial.getText().isEmpty()) {
            jOptionPane1.showMessageDialog(null, "Empty parameters");
        } else {
            username = jTextFieldInicial.getText();
            if (jPasswordInicial.getText().contains("&") || username.contains("&")) {
                jOptionPane1.showMessageDialog(null, "Invalid caracter '&'");
                return;
            }
            jOptionPane1.setVisible(false);
            password = MD5_hash.MD5_hash(jPasswordInicial.getText());
            System.out.println("Username: " + username);
            System.out.println("Hash: " + password);
            /*if (user!=null){
                try {
                    user.join();
                } catch (InterruptedException ex) {
                    Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }*/
            user = new User(username, password, null, null, null);
            System.out.println(user);
            try {
                user.sendData("Login");
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (user.getResultadoLogin() == 2) {
                    jOptionPane1.showMessageDialog(null, "Username not found!");
                } else if (user.getResultadoLogin() == 3) {
                    jOptionPane1.showMessageDialog(null, "Wrong Password!");
                } else {
                    setContentPane(Intro);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(UIinicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            jOptionPane1.setVisible(false);
            System.out.println(password);

            welcome1.setText("Welcome " + username + "!");
            backvalue = Inicial;
        }
    }//GEN-LAST:event_login1ActionPerformed

    private void forgotPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPwActionPerformed
        // TODO add your handling code here:

        ForgotPasswordSetDefault();
        setContentPane(ForgotPassword);
        invalidate();
        validate();
        backvalue = Inicial;
    }//GEN-LAST:event_forgotPwActionPerformed

    private void usernameTextSignup1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextSignup1FocusGained
        // TODO add your handling code here:
        usernameTextSignup1.setText("");
    }//GEN-LAST:event_usernameTextSignup1FocusGained

    private void usernameTextSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextSignup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextSignup1ActionPerformed

    private void jPasswordSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordSignupActionPerformed

    private void jPasswordField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField6FocusGained

    private void jPasswordField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField6ActionPerformed
        // TODO add your handling code here:
        jPasswordField6.setText("");
    }//GEN-LAST:event_jPasswordField6ActionPerformed

    private void InicialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicialMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_InicialMouseEntered

    private void InicialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicialMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_InicialMouseExited

    private void goback4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goback4ActionPerformed
        setContentPane(backvalue);
        backvalue = Inicial;
        invalidate();
        validate();
    }//GEN-LAST:event_goback4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIinicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            main.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Ads;
    private javax.swing.JScrollPane Ads1;
    private javax.swing.JFormattedTextField AnswerQuestionSignup;
    private javax.swing.JButton CreateGame1;
    private javax.swing.JPanel ForgotPassword;
    private javax.swing.JPanel GameJoined;
    private javax.swing.JPanel GuestIntro;
    private javax.swing.JPanel Inicial;
    private javax.swing.JPanel Intro;
    private javax.swing.JButton JoinGame;
    private javax.swing.JButton JoinGame1;
    private javax.swing.JButton PlayersOnline1;
    private javax.swing.JButton Rankings1;
    private javax.swing.JPanel Signup;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JFormattedTextField emailText1;
    private javax.swing.JFormattedTextField emailTextSignup;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton forgotPw;
    private javax.swing.JButton goback;
    private javax.swing.JButton goback1;
    private javax.swing.JButton goback2;
    private javax.swing.JButton goback3;
    private javax.swing.JButton goback4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JPasswordField jPasswordInicial;
    private javax.swing.JPasswordField jPasswordSignup;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextFieldInicial;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton login1;
    private javax.swing.JButton login2;
    private javax.swing.JButton login3;
    private javax.swing.JButton newAcc1;
    private javax.swing.JButton newAcc2;
    private javax.swing.JLabel password2;
    private javax.swing.JLabel password3;
    private javax.swing.JLabel password4;
    private javax.swing.JLabel password5;
    private javax.swing.JButton playGuest;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JFormattedTextField usernameText4;
    private javax.swing.JFormattedTextField usernameText5;
    private javax.swing.JFormattedTextField usernameTextSignup;
    private javax.swing.JFormattedTextField usernameTextSignup1;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcome1;
    private javax.swing.JLabel welcome2;
    // End of variables declaration//GEN-END:variables
}
